In [5]:
from gensim.models.word2vec import Word2Vec
from konlpy.tag import Okt

import pandas as pd

In [7]:
train = pd.read_csv('./nsmc/ratings_train.txt',sep='\t',encoding='utf8')
train = train.iloc[:, 1:]
train

                                                 document  label
0                                     아 더빙.. 진짜 짜증나네요 목소리      0
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2                                       너무재밓었다그래서보는것을추천한다      0
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...                                                   ...    ...
149995                                인간이 문제지.. 소는 뭔죄인가..      0
149996                                      평점이 너무 낮아서...      1
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 2 columns]

In [ ]:
sbs_df = pd.read_excel('./sbs_comment.xlsx')
sbs_df = sbs_df.iloc[:, 1:-2]
sbs_df.columns = (['document', 'label'])

In [ ]:
train_df = pd.concat([train, sbs_df])

In [ ]:
train_df.to_csv('./review_train_data.txt', index = False)

In [11]:
test_df = pd.read_csv('./review_test_data.txt')
test_df = test_df.iloc[:, 1:]
test_df

                                                document  label
0                                                    굳 ㅋ      1
1                                   GDNTOPCLASSINTHECLUB      0
2                 뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3                       지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...                                                  ...    ...
52035                         저걸 북한은 왜 중국한테 넘겨서.. 으.. 분통      0
52036                             괴물있는줄 알고 클릭했는데 도자기만 있네      0
52037              저기 동전 어마어마하게 많을텐뎁 여행객들이 동전던지고 기도하고그래서      1
52038                                             뭔 근물이여      0
52039                               물꼬기는 언제 들어간거임?!?! ㅋㅋ      1

[52040 rows x 2 columns]